### ISSUE TITLE
Create Project Admin Repo?

### ISSUE THREAD

**Issue by marchof** [jacoco/project-admin#1]
@Godin Hi Evgeny, I really get used to the discussions in issue and pull requests. It helps me to stay way more focussed and track open issues than with Email. What about using a separate repo to track project admin stuff like logos, web hosting or CI infrastructure?

**Comment by Godin** [comment]
@marchof Why not reuse issues in repository for site (currently inactive) instead of creation of a new empty repository? A kind of Occam's razor principle - don't multiply entities without necessity. On other side this looks like a not a bad idea.

**Comment by marchof** [comment]
@Godin Actually I haven't considered this. But from "separation of concerns" it should be a separate repo. Especially as I can imagine that we might have some docs here in future which should not be part of the website.

**Comment by Godin** [comment]
@marchof Ok, no pb - let's give it a try here.
