### ISSUE TITLE
Find Continuous Integration Hosting

### ISSUE THREAD

**Issue by marchof** [jacoco/project-admin#2]
Continuous integration should not only provide repository status, but also update snapshot builds.

**Comment by Godin** [comment]
@marchof Currently we utilize https://travis-ci.org/ for CI, but we can't use it for snapshot deployments as we don't want to publicly expose passwords. We should take a look on another public and free service - https://buildhive.cloudbees.com/ Also we can try to ask Cloudbees for a dedicated free account for FOSS project. Also we can imagine that public and free service will only do a CI (like now), but deployment of snapshot will be done in a private CI (for example at SonarSource). For the moment except of this I don't have other free proposals - other options will include payments.

**Comment by marchof** [comment]
The other issue with travis-ci is that they do not run tests.

The advantage of Cloudbees is that they already have hooks with Github. I would actually prefer to have a solution which also publishes snapshots. I can ask them for the FOSS plan.

I do not expect the CI infrastructure to be free (as beer). I could can also rent a EC2 instance.

**Comment by Godin** [comment]
In fact travis-ci should run tests and it tries to do so, but it does in two stages - compilation and tests. To confirm you can search for "mvn test" in log. But indeed for some reason such strategy doesn't work for us - I found this during release of 0.6.1 and should investigate.

Indeed - probably money isn't a big problem. But then my main concern is about maintenance costs and availability of time. From here SaaS is a good choice.

About Cloudbees - I'll investigate / ask since we have contacts with them.

**Comment by Godin** [comment]
@marchof FYI BuildHive is up and running for JaCoCo and EclEmma ( https://buildhive.cloudbees.com/job/jacoco/ ) and it perfectly executes tests. So we can slightly postpone why strategy used by travis-ci to execute tests doesn't work. And I'll work on the way to automate deployment.

**Comment by marchof** [comment]
Wow, that was fast! Can I put a link to this on the JaCoCo home page?

**Comment by Godin** [comment]
@marchof I think it's too early - let's wait a bit.

**Comment by Godin** [comment]
@marchof Now we have a FOSS account at Cloudbees ( http://www.cloudbees.com/foss/foss-dev.cb ) to perform automatic deployments of snapshots - https://jacoco.ci.cloudbees.com/ . I suggest to keep BuildHive for verification of pull requests and use this account only for deployments from master (ie. when pull request merged), so we will not consume more than free quota. Also FYI there some fans of JaCoCo in Cloudbees and they are pleased to help.

So the missing piece is an automatic deployment of site, but I hope to come up with solution as part of #4 or for the beginning based on SF as now, but automatic.

**Comment by Godin** [comment]
@marchof And we should update site by adding logo of Cloudbees ;) I'll work on that.

**Comment by Godin** [comment]
@marchof And some numbers: to build and deploy JaCoCo we consume around 17 minutes of m1.small instance, which allows us to do 110 builds per month or 3 builds per day for free, even not counting m1.large instance.

**Comment by marchof** [comment]
@Godin If required we can upgrade to the paid FOSS plan (15$/Month). We can add the Cloudbees logo to the page template and put in the left column, right above the "Java Experts" logo.

**Comment by marchof** [comment]
@Godin I found some time today to work add the CloudBees logo to our site.

**Comment by marchof** [comment]
Enhancement request for Java 5: https://cloudbees.zendesk.com/entries/21970769-Support-for-Java-5

**Comment by marchof** [comment]
Closing this as we have CI in place since quite some time.
