### ISSUE TITLE
JaCoCo trunk website update on SF

### ISSUE THREAD

**Issue by marchof** [jacoco/project-admin#5]
Hi Evgeny,

I added a new script at SF to upate the JaCoCo trunk website from the latest snapshot build -- until we have another web publishing machanism.

Is that o.k. for now?

Cheers,
-marc

**Comment by marchof** [comment]
@Godin I've just seen that there was a new snapshot build copied to SF file release system by user godin. Do you want to keep uploading to SF? From my understanding we now have CI at Cloudbees and Snapshot artifacts in the snapshot Maven repo.

**Comment by Godin** [comment]
@marchof This uploading was done, because I wasn't aware of this ticket and there were some undeployed changes, so I used old script to publish JaCoCo site. But indeed now I don't want to keep uploading to SF.

**Comment by marchof** [comment]
So we do manual updates with the new scripts until we have an automated web publishing solution in place.
