### ISSUE TITLE
Missing step in installing and configuring Jacoco for Linux (Fedora 20 at least)

### ISSUE THREAD

**Issue by mihaimaruseac** [jacoco/project-admin#6]
Hi,

I've tried using Jacoco (downloaded the jars in zip file from Maven) on Fedora 20 without Eclipse (I'm that guy which uses Vim for everything). Followed all the steps in http://www.eclemma.org/jacoco/trunk/doc/ant.html (dropped `jacocoant.jar` in `$ANT_HOME/lib`) but it still wouldn't work: ant would not find it.

After serious looking at the ant scripts and stracing it I found that I also had to edit `/etc/ant.d`: I had to create a file in there called `jacoco` which contained the line `jacoco ant/jacocoant`. Now it works properly.

**Comment by marchof** [comment]
Please report the issue to the Fedora package maintainer. Thx.

**Comment by mihaimaruseac** [comment]
There is no Fedora package that is self-contained. I was just suggesting an improvement on the site. Anyway, this is exactly Java people's answer everywhere.

**Comment by marchof** [comment]
Ok, I see. We can improve documentation here. Did you find a good web resource we could link to for Ant extensions on Fedora Linux?

**Comment by mihaimaruseac** [comment]
Closing it, now it seems to work properly.
